#ifndef MY_CERTIFICATES_H
#define MY_CERTIFICATES_H

// These are generated by xxd, see Readme or HttpsCertificateExtension.h for details
// Contains unencrypted client private key and certifiacate in DER format
extern unsigned char client_crt[];
extern int client_crt_len;
extern unsigned char client_key[];
extern int client_key_len;

#endif
